Squashed commit of the following:
commit 3211499a9ecee17da06c7a9a110770481ae102d5
Author: nerinabova <nerinabova@gmail.com>
Date:   Tue Sep 24 21:29:12 2024 -0300

    LoginWB

commit 470597d491e13286dc82bcb4eb37f63e0d3045d0
Author: nerinabova <nerinabova@gmail.com>
Date:   Tue Sep 24 21:27:25 2024 -0300

    Agregue webservice y dbhelper

commit 23f67bd25e007015bcf5f119bbde5cb46c28bef7
Author: nerinabova <nerinabova@gmail.com>
Date:   Mon Sep 23 11:56:18 2024 -0300

    Squashed commit of the following:

    commit 1c95c12b8f56f89f1f99e712178689e2a601ee71
    Author: brandansantiago <brandansantiago1998@gmail.com>
    Date:   Mon Sep 23 02:14:17 2024 -0300

        Nueva validación en capa de negocio para contraseña - V2

        Se agrega en la capa de negocio, en ValidacionesNegocio.cs una validación en el que la contraseña debe de contener como mínimo una letra mayúscula y un número

    commit c8e85741cd3092b72ab401af83f98e4dbd6d5769
    Author: brandansantiago <brandansantiago1998@gmail.com>
    Date:   Mon Sep 23 01:51:30 2024 -0300

        Nueva validación en capa de negocio para la contraseña

        Se agrega en la capa de negocio, en ValidacionesNegocio.cs una validación en el que la contraseña debe de tener entre 8 y 15 caracteres entre letras y números

    commit 0d2b54ac0d33094257c31bb330d29c3e238a203f
    Author: brandansantiago <brandansantiago1998@gmail.com>
    Date:   Mon Sep 23 01:31:25 2024 -0300

        Nueva validación en capa de negocio para el usuario

        Se agrega en la capa de negocio, en ValidacionesNegocio.cs una validación para que el usuario no pueda contener ni el nombre ni el apellido del usuario

    commit e126e007ce589479b77bfda28a399734ad3a1d3f
    Author: brandansantiago <brandansantiago1998@gmail.com>
    Date:   Mon Sep 23 01:04:39 2024 -0300

        Nueva validación en capa de negocio

        Se agrega en la capa de negocio, en ValidacionesNegocio.cs una validación para que el nombre de usuario contenga entre 8 y 15 caracteres.

    commit e9fe026b7f392fee7fac9a285082a72e7a70fbbc
    Author: brandansantiago <brandansantiago1998@gmail.com>
    Date:   Mon Sep 23 00:47:58 2024 -0300

        Cambio de nombre a clase + Incorporación de using en formulario de registro

        En la capa de negocio se cambia el nombre de la clase ValidacionesUtils.cs a ValidacionesNegocio.cs para que no se llame igual que ValidacionesUtils.cs de la capa de presentación.
        Se agrega en FrmRegistroUsuario.cs un using del namespace Negocio para poder llamar luego a las validaciones de la capa de Negocio.

    commit f45e9ff958620c252dc9c3ba730e915faac4ec0c
    Author: brandansantiago <brandansantiago1998@gmail.com>
    Date:   Sun Sep 22 19:56:03 2024 -0300

        Mejoras al idUsuario

        Se agrega un metodo para que se autoincremente el idUsuario por cada registro de usuario.

    commit 2faa669591872a8bc0bae74c98656bc75ba0ec77
    Author: brandansantiago <brandansantiago1998@gmail.com>
    Date:   Sun Sep 22 19:49:19 2024 -0300

        Creación de validación para registro de usuario

        Creación de lógica que valida si los campos del formulario FrmRegistroUsuario estan vacios. La validación se crea en ValidacionesUtils.cs de la capa presentación.
        Si se completan todos los campos el formulario permite el registro del usuario y si de todos los campos falta completar alguno, aparece un mensaje que le avisa a quien va a hacer el registro del usuario que le están faltando datos por completar para que se haga efectivo el registro. Cuando se registra el usuario el programa avisa que el mismo se ha registrado con exito.

    commit 3ab776c091a1fa2e4dea8162d08ef7a0bbf0bae3
    Author: brandansantiago <brandansantiago1998@gmail.com>
    Date:   Sun Sep 22 19:22:38 2024 -0300

        Creación de ID de usuario autoincremental en formulario de registro de usuario.

        Se crea una lógica en la cual en el formulario de registro de usuario el id de usuario se tiene que rellenar solo ante cada usuario que se registra.
        También se agrega una lógica para que este ID de usuario no se pueda editar de forma manual.

    commit 02a447bf100842a9ec8f0f62cf13cff61a3bbf48
    Author: brandansantiago <brandansantiago1998@gmail.com>
    Date:   Sun Sep 22 19:11:19 2024 -0300

        Arreglo de error de excepción producida en formulario de registro de usuario

        Cuando se escribe en FrmRegistroUsuario.cs, dentro del evento Click el siguiente script para tomar el valor ingresado en el comboBox:
        host = cmbHost.SelectedItem.ToString();

        El programa devuelve error de excepción producida:
        System.NullReferenceException: 'Referencia a objeto no establecida como instancia de un objeto.'

        System.Windows.Forms.ComboBox.SelectedItem.get devolvió null.

        Se arregla el error agregando al final de SelectedItem un signo de interrogación quedando el código de la siguiente forma en FrmRegistroUsuario.cs:
        host = cmbHost.SelectedItem?.ToString();
        Cuando se quiere confirmar el registro del usuario se comprueba que ya no devuelve más error.

    commit f51ef487f6de8bbd415ad6348e9b9b1285e13f06
    Author: brandansantiago <brandansantiago1998@gmail.com>
    Date:   Sun Sep 22 18:57:15 2024 -0300

        Creación de metodo Host

        Se crea un método para llenar el comboBox que se llama Host (del formulario de registro de usuarios) con sus posibles valores a elegir, entre ellos:
        Administrador (3),
        Supervisor (2),
        Vendedor (1).

    commit e06d8acae3928fbba6793ddbd98f9eddea789479
    Author: brandansantiago <brandansantiago1998@gmail.com>
    Date:   Sun Sep 22 18:48:52 2024 -0300

        Mejoras a formulario de registro de usuario

        Se asigna a cada textBox del formulario de registro de usuario sus nombres para identificarlos mejor.
        Se agrega una lógica .Text sobre cada variable del formulario de registro, para que se vayan tomando los valores que se van ingresando en cada TextBox del formulario.
        Se agrega mensaje de usuario registrado con exito.

    commit 5956bedff9090852b4b67de9e6abc5e0e8f02416
    Author: brandansantiago <brandansantiago1998@gmail.com>
    Date:   Sun Sep 22 18:35:00 2024 -0300

        Abrir formulario de registro y ocultar Menu anterior + Creación de variables

        Se agrega una lógica que hace lo siguiente: cuando se hace clic en Registrar Usuario en el formulario FrmMenuAdmin.cs, este ultimo se oculta y se abre el nuevo formulario de registro.
        Tambien en el formulario FrmRegistroUsuario se crean las variables necesarias (nombre, apellido, direccion, telefono, email, usuario, host, dni, contraseña).

    commit 5042f3e850284a6d8d56e892fa0f97c9383d420a
    Author: brandansantiago <brandansantiago1998@gmail.com>
    Date:   Sun Sep 22 18:26:01 2024 -0300

        Creación de FrmRegistroUsuario.cs

        Se crea el formulario para registrar usuarios con sus botones.

    commit 3649103fb83ecb7fd2f638447d83d28e2a5fb1e1
    Author: brandansantiago <brandansantiago1998@gmail.com>
    Date:   Thu Sep 19 00:05:28 2024 -0300

        Nuevo formulario y mejora a formularios existentes.

        Creacion de formulario FrmMenuVendedor.cs y botones en el mismo.
        Cambio de names/nombres de formularios existentes.
        Se agrega un this.Hide(); sobre Login.cs una vez que el usuario se loguea para ocultar formulario de Login.
        Creación de botones en formulario FrmMenuAdmin.cs

    commit c07be97a2ef21d530fcae4c3630493e8bdaccad2
    Author: brandansantiago <brandansantiago1998@gmail.com>
    Date:   Wed Sep 18 21:43:54 2024 -0300

        Creación FrmMenuSupervisor

        Creación del form menú supervisor. Creación de botones en formulario.

commit 7381d865d228dd096e0ae7f3a381d264f325fff0
Author: nerinabova <nerinabova@gmail.com>
Date:   Fri Sep 20 21:46:41 2024 -0300

    Creación de Rama